gesdinet_jwt_refresh_token:
    ttl: 2592000 # 30 jours
    single_use: true
    token_parameter_name: refresh_token
    refresh_token_class: App\Entity\RefreshToken  # <-- change selon ton entité
    object_manager: doctrine.orm.entity_manager