webauthn:
    credential_repository: App\Repository\WebauthnCredentialRepository
    user_repository: App\Repository\UserRepository
    creation_profiles:
        default:
            rp:
                name: '%env(RELYING_PARTY_NAME)%'
                id: '%env(RELYING_PARTY_ID)%'
    request_profiles:
        default:
            rp_id: '%env(RELYING_PARTY_ID)%'