services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      APP_DOMAIN: ${APP_DOMAIN}
      DATABASE_URL: mysql://user:password@db:3306/reservation_db
    volumes:
      - ./config/jwt:/var/www/config/jwt:ro
      - ./var:/var/www/var
      - ./:/var/www
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: reservation_db
    environment:
      MYSQL_DATABASE: reservation_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: