parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # PLUS DE LIGNE "services:" ICI
    App\Service\PasskeyAuthService:
        arguments:
            $webauthnServer:  '@webauthn.server'
            $session: '@session'
            $credRepo: '@App\Repository\WebauthnCredentialRepository'